# API için Dockerfile

FROM python:3.11

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --no-root

COPY . .

# Poetry komutlarını çalıştırabilmek için poetry yolu ekle
ENV PATH="/root/.local/bin:${PATH}"

# API uygulamasını çalıştır
CMD ["uvicorn", "phishing_service.api:app", "--host", "0.0.0.0", "--port", "8000"]
