version: "3.11"
services:
  db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5432:5432"

  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app

  api-app:
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
    ports:
      - "8000:8000"
